'use client';
import { useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { Upload, Sparkles, Download, FileSpreadsheet, AlertTriangle, CheckCircle2, Users, GraduationCap, Languages, ChevronDown, Clock3, Building2 } from 'lucide-react';

type Row={day:string;time:string;teacher:string;module:string;group:string;room:string;status?:'ok'|'conflict'};
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday'];
const slots=['08:00–09:30','09:30–11:00','11:00–12:30','13:30–15:00','15:00–16:30'];
const demo:Row[]=[
 {day:'Sunday',time:'08:00–09:30',teacher:'Dr. Ahmed Benali',module:'Database Systems',group:'L2-G1',room:'Lab 2'},
 {day:'Sunday',time:'09:30–11:00',teacher:'Dr. Sara Mansouri',module:'Networks',group:'L2-G2',room:'Room 12'},
 {day:'Monday',time:'08:00–09:30',teacher:'Dr. Ahmed Benali',module:'Database Systems',group:'L2-G2',room:'Lab 2'},
 {day:'Monday',time:'11:00–12:30',teacher:'Dr. Sara Mansouri',module:'Networks',group:'L2-G1',room:'Room 12'},
 {day:'Tuesday',time:'08:00–09:30',teacher:'Dr. Karim Haddad',module:'Algorithms',group:'L1-G1',room:'Room 8'},
 {day:'Tuesday',time:'09:30–11:00',teacher:'Dr. Nadia Kaci',module:'English',group:'L1-G2',room:'Room 6'},
 {day:'Wednesday',time:'08:00–09:30',teacher:'Dr. Karim Haddad',module:'Algorithms',group:'L1-G2',room:'Room 8'},
 {day:'Thursday',time:'13:30–15:00',teacher:'Dr. Nadia Kaci',module:'English',group:'L1-G1',room:'Room 6'},
];

export default function Home(){
 const [lang,setLang]=useState<'EN'|'FR'>('EN'); const [view,setView]=useState<'student'|'teacher'>('student'); const [rows,setRows]=useState<Row[]>(demo); const [generated,setGenerated]=useState(true); const [file,setFile]=useState('Demo university data');
 const t=lang==='EN'?{brand:'SchedulAI',sub:'University scheduling assistant',hero:'Build conflict-free university timetables.',desc:'Upload your existing Excel data. SchedulAI organizes classes, detects conflicts, and creates clear schedules for students and teachers.',upload:'Upload Excel file',demo:'Use demo data',generate:'Generate timetable',student:'Student timetable',teacher:'Teacher timetable',conflicts:'Conflicts',classes:'Classes scheduled',teachers:'Teachers',rooms:'Rooms used',export:'Export Excel',print:'Print / PDF',ready:'Schedule ready',note:'AI-assisted planning • deterministic conflict checks'}:{brand:'SchedulAI',sub:'Assistant de planification universitaire',hero:'Créez des emplois du temps sans conflits.',desc:'Importez vos données Excel. SchedulAI organise les cours, détecte les conflits et crée des emplois du temps clairs pour les étudiants et les enseignants.',upload:'Importer un fichier Excel',demo:'Utiliser les données démo',generate:'Générer l’emploi du temps',student:'Emploi du temps étudiant',teacher:'Emploi du temps enseignant',conflicts:'Conflits',classes:'Cours planifiés',teachers:'Enseignants',rooms:'Salles utilisées',export:'Exporter Excel',print:'Imprimer / PDF',ready:'Emploi du temps prêt',note:'Planification assistée par IA • vérification déterministe des conflits'};
 const conflicts=useMemo(()=>rows.filter(r=>r.status==='conflict').length,[rows]);
 function upload(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0]; if(!f)return; setFile(f.name); const reader=new FileReader(); reader.onload=ev=>{try{const wb=XLSX.read(ev.target?.result,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const data=XLSX.utils.sheet_to_json<Record<string,unknown>>(ws); const mapped=data.map((x,i)=>({day:String(x.Day||x.day||days[i%5]),time:String(x.Time||x.time||slots[i%5]),teacher:String(x.Teacher||x.teacher||'Teacher'),module:String(x.Module||x.module||'Module'),group:String(x.Group||x.group||'G1'),room:String(x.Room||x.room||'Room')})); if(mapped.length)setRows(mapped); }catch{} }}; reader.readAsArrayBuffer(f); }
 function exportXlsx(){const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Timetable');XLSX.writeFile(wb,'university-timetable.xlsx');}
 function generate(){setGenerated(false);setTimeout(()=>setGenerated(true),650)}
 const display= view==='student'?rows:rows.map(r=>({...r,group:r.teacher}));
 return <main><header><div className="brand"><div className="logo"><Sparkles size={18}/></div><div><b>{t.brand}</b><span>{t.sub}</span></div></div><div className="header-actions"><button className="lang" onClick={()=>setLang(lang==='EN'?'FR':'EN')}><Languages size={16}/>{lang}</button><button className="avatar">A</button></div></header>
 <section className="hero"><div><div className="eyebrow">UNIVERSITY OPERATIONS</div><h1>{t.hero}</h1><p>{t.desc}</p><div className="actions"><label className="primary"><Upload size={18}/>{t.upload}<input type="file" accept=".xlsx,.xls,.csv" onChange={upload}/></label><button className="secondary" onClick={()=>{setRows(demo);setFile('Demo university data')}}>{t.demo}</button></div><div className="fileline"><FileSpreadsheet size={15}/>{file}</div></div><div className="hero-card"><div className="mini-top"><span>AI PLANNER</span><span className="pulse"><i/> Ready</span></div><div className="planner"><div><small>Teachers</small><strong>24</strong></div><div><small>Groups</small><strong>18</strong></div><div><small>Rooms</small><strong>12</strong></div></div><div className="mini-line"><span>Constraint engine</span><b>Active</b></div><div className="mini-line"><span>Conflict checking</span><b>Automatic</b></div></div></section>
 <section className="workspace"><div className="toolbar"><div><h2>{t.ready}</h2><p>Academic year • Weekly schedule</p></div><button className="generate" onClick={generate}><Sparkles size={16}/>{generated?t.generate:'Generating…'}</button></div>
 <div className="stats"><Stat icon={<AlertTriangle/>} label={t.conflicts} value={conflicts} bad={conflicts>0}/><Stat icon={<Clock3/>} label={t.classes} value={rows.length}/><Stat icon={<Users/>} label={t.teachers} value={new Set(rows.map(r=>r.teacher)).size}/><Stat icon={<Building2/>} label={t.rooms} value={new Set(rows.map(r=>r.room)).size}/></div>
 <div className="viewbar"><div className="tabs"><button className={view==='student'?'active':''} onClick={()=>setView('student')}><GraduationCap size={16}/>{t.student}</button><button className={view==='teacher'?'active':''} onClick={()=>setView('teacher')}><Users size={16}/>{t.teacher}</button></div><div className="export"><button onClick={exportXlsx}><Download size={15}/>{t.export}</button><button onClick={()=>window.print()}>{t.print}</button></div></div>
 <div className="tablewrap"><table><thead><tr><th>Day</th><th>Time</th><th>{view==='student'?'Module':'Teacher'}</th><th>{view==='student'?'Teacher':'Module'}</th><th>Group</th><th>Room</th></tr></thead><tbody>{display.map((r,i)=><tr key={i}><td><span className="day">{r.day}</span></td><td>{r.time}</td><td><b>{view==='student'?r.module:r.teacher}</b></td><td>{view==='student'?r.teacher:r.module}</td><td><span className="tag">{r.group}</span></td><td>{r.room}</td></tr>)}</tbody></table></div>
 <div className="insight"><div className="insight-icon"><Sparkles size={17}/></div><div><b>Scheduling assistant</b><p>No hard conflicts detected in the demo dataset. When you upload your university file, the engine will check teacher, group, room, capacity and availability constraints.</p></div></div>
 </section><footer>{t.note}<span>SchedulAI MVP</span></footer></main>
}
function Stat({icon,label,value,bad}:{icon:React.ReactNode;label:string;value:number;bad?:boolean}){return <div className="stat"><div className={bad?'stat-icon bad':'stat-icon'}>{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>}
